database:
  mongo:
    url: sensitive
middlewares:
  cors:
    activate: true
    origin: '*'
    methods:
      - GET
      - POST
      - PUT
      - DELETE
    allowedHeaders: 
routing:
  base: '/api/v1'
# port: 8088
jsonLimit: 5mb

